### ISSUE TITLE
Are you back :D

### ISSUE THREAD

**Issue by di48l069** [vradinolfi/Transmute-v5#1]
Hey @vradinolfi  are you back at this project?

**Comment by vradinolfi** [comment]
I'm trying to get back into it! Last year I didn't spend nearly as much time as I wanted, so I'm trying to turn that around this year.

**Comment by di48l069** [comment]
I really hope you do it has potential bro

Get Outlook for Android<https://aka.ms/ghei36>




On Mon, Jan 23, 2017 at 9:37 PM +0200, "Vincent Adinolfi" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm trying to get back into it! Last year I didn't spend nearly as much time as I wanted, so I'm trying to turn that around this year.
